{% set name = "xraylarch" %}
{% set version = "0.9.72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bf2b6fcd9d19d3c30b0e5b3cca495019e0d208b17616ed9f7bbf6f78607484b
  patches:
    - 0001-PKG-patch-package_data.patch

build:
  number: 0
  entry_points:
    - larch = larch.apps:run_larch
    - larch_server = larch.apps:run_larch_server
    - feff6l = larch.apps:run_feff6l
    - feff8l = larch.apps:run_feff8l
    - xas_viewer = larch.apps:run_xas_viewer
    - larix = larch.apps:run_larix
    - gse_mapviewer = larch.apps:run_gse_mapviewer
    - larch_xrf = larch.apps:run_larch_xrf
    - epics_xrf = larch.apps:run_epics_xrf
    - larch_xrd1d = larch.apps:run_larch_xrd1d
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]


requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    # setup.py -> install_requires
    - packaging
    - pip
    - pyyaml
    - toml
    - pytest
    - termcolor
    - scipy >=1.7
    - numpy >=1.20
    - matplotlib-base >=3.5
    - sqlalchemy >=2.0
    - sqlalchemy-utils
    - h5py >=3.2
    - pillow >=8.3.2
    - psycopg2-binary
    - dill
    - imageio
    - charset-normalizer
    - peakutils
    - requests
    - scikit-image
    - scikit-learn
    - asteval >=0.9.28
    - lmfit >=1.2.0
    - uncertainties >=3.1
    - pyshortcuts >=1.9.0
    - xraydb >=4.5
    - silx >=0.15.2
    - hdf5plugin
    - numdifftools
    - psutil
    - pymatgen
    - fabio
    - pyfai
    - numexpr ==2.8.4  # [py<39]
    - numexpr >=2.8.7  # [py>38]
    - pycifrw
    - importlib-metadata  # [py<38]
    - pyopencl
    # From requirements-extra.txt
    - wxpython>=4.1
    - wxutils>=0.3.0
    - wxmplot>=0.9.53
    - pyepics>=3.5.0
    # Not available in conda-forge:
    # - epicsapps
    # From larch/site_config.py -> extra_pymatgen
    - mp-api
    - pandas
    - py3dmol
    # From installers/GetLarch.sh
    - mkl_fft
    - tomopy
    # From https://github.com/xraypy/xraylarch/blob/master/doc/installation.rst#installing-into-an-existing-anaconda-python-environment
    - openbabel

test:
  imports:
    - larch
  commands:
    # - pip check
    - larch --help
    - larch_server --help
    - feff6l --help
    - feff8l --help
    - xas_viewer --help
    - larix --help
    - gse_mapviewer --help
    - larch_xrf --help
    # - epics_xrf
    # - larch_xrd1d
  requires:
    # - pip

about:
  home: https://xraypy.github.io/xraylarch
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Larch: X-ray Analysis for Synchrotron Applications using Python'
  doc_url: https://xraypy.github.io/xraylarch
  dev_url: https://github.com/xraypy/xraylarch

extra:
  recipe-maintainers:
    - maurov
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
