{% set name = "xraylarch" %}
{% set version = "0.9.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb2ce75b6970631c0388a15967ee4a26d15d35ae38cb75655e7a38d7aed49570
  patches:
    - 0001-PKG-patch-package_data.patch

build:
  number: 0
  entry_points:
    - larch = larch.apps:run_larch
    - larch_server = larch.apps:run_larch_server
    - feff6l = larch.apps:run_feff6l
    - feff8l = larch.apps:run_feff8l
    - xas_viewer = larch.apps:run_xas_viewer
    - gse_mapviewer = larch.apps:run_gse_mapviewer
    - xrfdisplay = larch.apps:run_xrfdisplay
    - xrfdisplay_epics = larch.apps:run_xrfdisplay_epics
  script: |
    {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - asteval >=0.9.18
    - cchardet
    - fabio
    - h5py >=2.8
    - importlib-metadata
    - lmfit >=1.0
    - matplotlib-base >=3.0
    - numdifftools
    - numpy >=1.7
    - peakutils >=1.0.0
    - pillow >=3.4
    - psutil
    - pyFAI
    - pymatgen
    - pyshortcuts >=1.7.2
    - pytest
    - pyyaml
    - requests >=2.1
    - scikit-image
    - scikit-learn
    - scipy >=1.2
    - silx >=1.0
    - six >=1.10
    - sqlalchemy >=0.9
    - termcolor
    - toml
    - uncertainties
    - wxmplot
    - wxpython
    - wxutils
    - xraydb >=4.3

test:
  imports:
    - larch
    - larch.bin
  commands:
    # - pip check
    - larch --help
    - larch_server --help
    - feff6l --help
    - feff8l --help
    - xas_viewer --help
    - gse_mapviewer --help
    - xrfdisplay --help
    - xrfdisplay_epics --help || echo 'Failed, but RC=0'    # [not win or osx]
  requires:
    # - pip
    - psycopg2-binary
    - pycifrw
    - pyepics

about:
  home: https://xraypy.github.io/xraylarch
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Larch: X-ray Analysis for Synchrotron Applications using Python'
  doc_url: https://xraypy.github.io/xraylarch
  dev_url: https://github.com/xraypy/xraylarch

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
