{% set name = "xraylarch" %}
{% set version = "0.9.74" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40c7e821170d7290c87db522e96761853390c29782858a87bccd5b64c3f8ae5e

build:
  number: 0
  skip: true  # [py<37]

outputs:
  - name: xraylarch-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      entry_points:
        - larch = larch.apps:run_larch
        - feff6l = larch.apps:run_feff6l
        - feff8l = larch.apps:run_feff8l
        - larch_server = larch.apps:run_larch_server
        - larix = larch.apps:run_larix
        - xasviewer = larch.apps:run_xas_viewer
        - larch_xrf = larch.apps:run_larch_xrf
        - larch_xrd1d = larch.apps:run_larch_xrd1d
        - gse_mapviewer = larch.apps:run_gse_mapviewer
        - epics_xrf = larch.apps:run_epics_xrf
    requirements:
      host:
        - python
        - pip
        - setuptools_scm
      run:
        - python
        - asteval >=0.9.28
        - numpy >=1.20
        - scipy >=1.7
        - uncertainties >=3.1.4
        - lmfit >=1.2.1
        - uncertainties >=3.1
        - pyshortcuts >=1.9.0
        - xraydb >=4.5
        - silx-base >=0.15.2
        - matplotlib-base >=3.5
        - sqlalchemy >=2.0
        - sqlalchemy-utils
        - h5py >=3.2
        - hdf5plugin
        - pillow >=8.3.2
        - numdifftools
        - pandas
        - packaging
        - pip
        - pyyaml
        - toml
        - termcolor
        - dill
        - imageio
        - charset-normalizer
        - peakutils
        - requests
        - scikit-image
        - scikit-learn
        - psutil
        - pymatgen
        - mp-api
        - pycifrw
        - fabio
        - pyfai-base
        - numexpr ==2.8.4  # [py<39]
        - numexpr >=2.8.7  # [py>38]
    test:
      imports:
        - larch
      #commands:
      #  - pip check
      #requires:
      #  - pip

  - name: xraylarch
    build:
      noarch: generic
    requirements:
      host:
        - python
      run:
        - python
        - silx
        - pyfai
        # wxgui extras_require
        - wxpython >=4.1
        - wxutils >=0.3.0
        - wxmplot >=0.9.57
        # qtgui extras_require
        - pyqt
        - pyqtwebengine
        - pyqtgraph
        # jupyter extras_require
        - jupyter_core >=5.0
        - jupyter_client
        - jupyter_server
        - notebook
        - nbformat
        - ipywidgets
        - plotly
        - py3dmol
        - {{ pin_subpackage('xraylarch-base', max_pin="x.x.x") }}
    test:
      imports:
        - larch
      commands:
        - larch --help
        - feff6l --help
        - feff8l --help
        - larch_server --help
        - larix --help
        - xasviewer --help
        - larch_xrf --help
        # - larch_xrd1d
        - gse_mapviewer --help
        # - epics_xrf

about:
  home: https://xraypy.github.io/xraylarch
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Larch: X-ray Analysis for Synchrotron Applications using Python'
  doc_url: https://xraypy.github.io/xraylarch
  dev_url: https://github.com/xraypy/xraylarch

extra:
  recipe-maintainers:
    - maurov
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
